# Site settings
title1: ""
title2: "1st Workshop on Non-Binary Representation in Language Technologies"
email: "nbreplangtech [at] gmail.com" 
baseurl: ""
url1: ""
url2: "http://nbreplangtech.github.io"

# Build settings
markdown: kramdown
permalink: pretty
